---
apiVersion: v1
kind: Namespace
metadata:
  name: consul

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: consul
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: consul
    namespace: consul

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      serviceAccountName: consul
      containers:
        - name: consul
          image: consul:latest
          ports:
            - containerPort: 8500
              name: http
            - containerPort: 8300
              name: server
            - containerPort: 8301
              name: serflan-tcp
            - containerPort: 8302
              name: serflan-udp
            - containerPort: 8600
              name: dns
              protocol: UDP
          args:
            - "agent"
            - "-server"
            - "-bootstrap"
            - "-ui"
            - "-client=0.0.0.0"
            - "-bind=0.0.0.0"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
